version: 2.1

executors:
  android-executor:
    docker:
      - image: cimg/android:2024.04-node
    resource_class: medium

jobs:
  test:
    executor: android-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-v1-{{ checksum "gradle/libs.versions.toml" }}
            - gradle-v1-
      - run:
          name: Grant execute permissions for gradlew
          command: chmod +x ./gradlew
      - run:
          name: Run Unit Tests for All Modules
          command: ./gradlew testDebugUnitTest --continue
      - save_cache:
          key: gradle-v1-{{ checksum "gradle/libs.versions.toml" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
      - store_test_results:
          path: app/build/test-results
      - store_test_results:
          path: core/build/test-results
      - store_test_results:
          path: favorite/build/test-results
      - store_artifacts:
          path: app/build/reports/tests/testDebugUnitTest
          destination: reports/app-tests
      - store_artifacts:
          path: core/build/reports/tests/testDebugUnitTest
          destination: reports/core-tests
      - store_artifacts:
          path: favorite/build/reports/tests/testDebugUnitTest
          destination: reports/favorite-tests

  build-apk:
    executor: android-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-v1-{{ checksum "gradle/libs.versions.toml" }}
            - gradle-v1-
      - run:
          name: Grant execute permissions for gradlew
          command: chmod +x ./gradlew
      - run:
          name: Build Debug APK
          command: ./gradlew assembleDebug
      - save_cache:
          key: gradle-v1-{{ checksum "gradle/libs.versions.toml" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apk-debug

workflows:
  build_and_test:
    jobs:
      - test
      - build-apk:
          requires:
            - test
